- appveyor.yml
Added `appveyor.yml` config file to run unit tests.
> [MSYS-715]Setup appveyor 

- README.md
- lib/win32/certstore/mixin/crypto.rb
- lib/win32/certstore/store_base.rb
- spec/win32/unit/certstore_spec.rb
Update the Readme and fix bug for cert_delete functionality
> [MSYS-741] Update the Readme and fix bug for cert_delete functionality

- lib/win32/certstore/store_base.rb
- spec/win32/unit/certstore_spec.rb
This method delete certificate from open certificate store by using thumbprint and return boolean.
**Usages:**
```
thumbprint = "‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe"
Win32::Certstore.open("ROOT") do |store|
store.delete(thumbprint)
end
```
**Return:**.
```
True
```
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
> Delete certificate by thumbprint

- .rubocop.yml
- .travis.yml
- lib/win32/certstore.rb
- lib/win32/certstore/mixin/assertions.rb
- lib/win32/certstore/mixin/crypto.rb
- lib/win32/certstore/mixin/helper.rb
- lib/win32/certstore/mixin/shell_out.rb
- lib/win32/certstore/store_base.rb
- spec/win32/unit/certstore_spec.rb
**Description**
- Update travis for ruby version (2.2.0, 2.3.3, 2.4.1 and 2.5.1)
- Added Chefstyle in Travis.
**Issue fixed:**
Fixes: https://github.com/chef/win32-certstore/issues/28
Fixes: https://github.com/chef/win32-certstore/issues/29
Signed-off-by: piyushawasthi piyush.awasthi@msystechnologies.com
> [MSYS-837] Update Travis for Ruby multiple version and add Chefstyle to Travis

- .expeditor/config.yml
- .travis.yml
> Cleanup deprecated configs in expeditor

- .expeditor/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- Gemfile
- win32-certstore.gemspec
Aligning this gem with our other gems
> Update expeditor config and gemfile groups

- win32-certstore.gemspec
> Add missing license directive in the gemspec

- appveyor.yml
> Add Ruby 2.5 testing in Appveyor

- .travis.yml
- win32-certstore.gemspec
This allows us to test this gem on bundler 2.x installs.
> Unpin the bundler dev dep

- .expeditor/config.yml
- .travis.yml
- appveyor.yml
Make sure we keep things green here.
> Add chefstyle testing in appveyor / travis

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
- README.md
- Rakefile
- lib/win32/certstore/mixin/crypto.rb
- lib/win32/certstore/mixin/shell_out.rb
- lib/win32/certstore/store_base.rb
The first PR was necessary to create the pipeline. This PR will actually
get it green.
> Update testing for Buildkite

- spec/spec_helper.rb
- win32-certstore.gemspec
Expand on the dir not the file
> Simplify our use of expand_path

- spec/win32/unit/certstore_spec.rb
Signed-off-by: John McCrae <john.mccrae@progress.com>
> updated the unit tests to verify connecting to the CurrentUser store

- .expeditor/verify.pipeline.yml
- spec/win32/unit/certstore_spec.rb
> Updated the expeditor verify pipeline to test against Ruby 3.0

- lib/win32/certstore.rb
- lib/win32/certstore/mixin/helper.rb
- lib/win32/certstore/mixin/string.rb
- lib/win32/certstore/store_base.rb
- spec/win32/functional/win32/certstore_spec.rb
- spec/win32/unit/certstore_spec.rb
Signed-off-by: John McCrae <jmccrae@chef.io>
> Updated Certstore to correctly understand CurrentUser vs LocalMachine stores

- lib/win32/certstore/store_base.rb
Signed-off-by: John McCrae <john.mccrae@progress.com>
> Refactored cert_get to return x509 object

- win32-certstore.gemspec
Signed-off-by: John McCrae <john.mccrae@progress.com>
> Updated the gem to reflect an update to the chef-powershell gem

- .expeditor/verify.pipeline.yml
Signed-off-by: skeshari12 <skeshari@msystechnologies.com>
> Add ruby 3.1 test

- lib/win32/certstore/store_base.rb
- spec/win32/unit/certstore_spec.rb
Signed-off-by: John McCrae <jmccrae@chf.io>
> Reverting the error handling for a missing item on cert_lookup

- lib/win32/certstore/mixin/assertions.rb
- lib/win32/certstore/mixin/helper.rb
Signed-off-by: John McCrae <jmccrae@chf.io>
> refactoring to correct for not finding certs correctly in some cases.

- .expeditor/verify.pipeline.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- .rubocop.yml
- Gemfile
- Rakefile
- lib/win32/certstore/store_base.rb
- win32-certstore.gemspec
Updating Ruby support to version 3.4 and Cookstyle support v 8.1 and later.
> Updating Ruby support and Cookstyle support
