lib/win32/certstore.rb, lib/win32/certstore/store_base.rb
In this PR I resolved the error which I was getting during loading 'win32-certstore' library. I was getting 'cannot load such file error certstore/mixin/crypto' in [certstore.rb](https://github.com/chef/win32-certstore/blob/master/lib/win32/certstore.rb#L18) while requiring 'win32-certsore' libraray.
Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>
=> [MSYS-720]Resolved cannot load such file 'certstore/mixin/crypto' error

lib/win32/certstore.rb, lib/win32/certstore/mixin/crypto.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
Added code to delete single certificate from cert_store.
We can delete the certificate & check as: 
```
store = Win32::Certstore.open("root")
cert = store.delete('Frank4DD Web CA')
puts "output : #{cert}"
```
=> [MSYS-545] Add code to delete certificate from cert_store.

lib/win32/certstore.rb, lib/win32/certstore/mixin/crypto.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
We can retrieve properties of specific certificate with ruby code as: 
```
store = Win32::Certstore.open("MY")
a = store.retrieve('Frank4DD Web CA')
p "o/p : #{a}"	
```
and get output in format as : 
```
"o/p : {:CERT_NAME_EMAIL_TYPE=>\"support@frank4dd.com\", :CERT_NAME_RDN_TYPE=>\"JP, Tokyo, Chuo-ku, Frank4DD, WebCert Support, Frank4DD Web CA, support@frank4dd.com\", :CERT_NAME_ATTR_TYPE=>\"
support@frank4dd.com\", :CERT_NAME_SIMPLE_DISPLAY_TYPE=>\"Frank4DD Web CA\", :CERT_NAME_FRIENDLY_DISPLAY_TYPE=>\"Frank4DD Web CA\", :CERT_NAME_DNS_TYPE=>\"Frank4DD Web CA\", :CERT_NAME_URL_TYP
E=>\"\", :CERT_NAME_UPN_TYPE=>\"\"}"
```
=> [MSYS-544]: Retrieve properties of a single certificate

lib/win32/certstore.rb, lib/win32/certstore/mixin/assertions.rb, lib/win32/certstore/mixin/helper.rb, lib/win32/certstore/mixin/shell_out.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
**Note:** First merge PR: #16 after that need to rebase this branch.
This method get certificate using thumbprint and return OpenSSL::X509 certificate object.
**Usages:**
```
thumbprint = "‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe"
Win32::Certstore.open("ROOT") do |store|
cert_obj = store.get("‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe")
store.close
end
```
**Note:**  Here cert_obj is OpenSSL::X509 certificate object as.
```
#<OpenSSL::X509::Certificate
subject=#<OpenSSL::X509::Name CN=GlobalSign Root CA,OU=Root CA,O=GlobalSign nv-sa,C=BE>,
issuer=#<OpenSSL::X509::Name CN=GlobalSign Root CA,OU=Root CA,O=GlobalSign nv-sa,C=BE>,
serial=#<OpenSSL::BN 4835703278459707669005204>,
not_before=1998-09-01 12:00:00 UTC,
not_after=2028-01-28 …
```
=> [MSYS-769] Win32-certstore - get certificate

lib/win32/certstore.rb, lib/win32/certstore/mixin/helper.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
**Note:** First merge PR: #16 after that need to rebase this branch.
This method verify certificate using thumbprint and return boolean.
**Usages:**
```
thumbprint = "‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe"
Win32::Certstore.open("ROOT") do |store|
cert_obj = store.verify("‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe")
store.close
end
```
**Return:**.
```
True
```
=> MSYS-547: [win32-certstore] Verify Certificate

lib/win32/certstore.rb, lib/win32/certstore/mixin/assertions.rb, lib/win32/certstore/mixin/crypto.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
**Note:** First merge PR: #16 after that need to rebase this branch.
This method search certificate by CN, Friendly_name, Simple_display_name, DNS, URL, UPN and other attributes and return match certificate hash.
**Usages:**
```
Win32::Certstore.open("ROOT") do |store|
search_certificate_data = store.search("GlobalSign Root CA")
store.close
end
```
**Note:**  Here search_certificate_data is Hash that contain Friendly_name and RDN Like:.
```
certificate_list{ certificate1: {friendly_name: "Friendly Name", rdn: "RDN"}, certificate2: {friendly_name: "Friendly Name", rdn: "RDN"}, ..}
```
=> [MSYS-767] Win32-certstore - search certificate.

lib/win32/certstore.rb, lib/win32/certstore/mixin/assertions.rb
- Added support Ruby 2.0 also add more valid store same as windows cookbooks. 
- Fixed FFI destroy object messages
**Issues:**
- Fixes: https://github.com/chef/win32-certstore/issues/27
- Fixes: https://github.com/chef/win32-certstore/issues/30
Signed-off-by: piyushawasthi piyush.awasthi@msystechnologies.com
=> [MSYS-836] fixes for ruby2.0 and FFI destroy object messages 

lib/win32/certstore.rb, lib/win32/certstore/mixin/crypto.rb, spec/win32/unit/certstore_spec.rb
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
Fixed confirmation popup while installing certificate in root also fixed certificate be installed in the personal local computer
Fixes https://github.com/chef-cookbooks/windows/issues/561
Fixes https://github.com/chef-cookbooks/windows/issues/566
=> Fixed MSYS-857 & MSYS-838 

lib/win32/certstore/mixin/assertions.rb, spec/win32/unit/certstore_spec.rb, spec/win32/unit/store/assertions_spec.rb
Removed store validation, Now if user open any store that not exist and want to add new certificate in that then our code will create new store for user and add new certificate in that.
Issue: https://github.com/chef-cookbooks/windows/issues/565
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
=> MSYS-856 : Removed store validation

lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
If user pass invalid thumb-print it's throw an error `OpenSSL::X509::CertificateError - Header Too Long`
Fixes : https://github.com/chef-cookbooks/windows/issues/569
StackOverflow discussion that's relevant]
=> Delete certificate raise an exception if user pass invalid thumbprint

win32-certstore.gemspec
We need a license file for our license enforcement application.
=> Update the gemspec to skip the readme, but ship the license

lib/win32/certstore.rb, lib/win32/certstore/mixin/helper.rb, lib/win32/certstore/store_base.rb, spec/win32/functional/win32/certstore_spec.rb
Signed-off-by: vasu1105 <vasundhara.jagdale@msystechnologies.com>
Currently get method for certificate store not getting the certificate from particular store. It finds it from all stores. Since we are performing operations by opening specific store we should modify the get method have same behaviour. Otherwise when we want to find if there is any certificate available in given store it will always return true because the same certificate is available in another store. 
This fix needs to be added first to fix the https://github.com/chef-cookbooks/windows/issues/578 completely.
=> Fixes certificate get method to fetch certificate from given store.

win32-certstore.gemspec
There's no executables in this gem so there's no reason to define this here.
=> Remove unnecessary config in the gemspec

.travis.yml, appveyor.yml, win32-certstore.gemspec
Update the gemspec to require Ruby 2.2 or later
Update the author of the gem to be Chef Software
Add Ruby 2.6 testing Travis
Add Ruby 2.3 testing in Appveyor
=> Require ruby 2.3 or later

lib/win32/certstore/mixin/crypto.rb, lib/win32/certstore/mixin/unicode.rb, lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb
- Fix deletion of a certificate by its thumbprint.
- Fetch correct certificate from the given store by its thumbprint.
- Fixes: [576](https://github.com/chef-cookbooks/windows/issues/576)
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>
Used `CRYPT_HASH_BLOB` structure which takes `thumbprint` as an input and using this struct with `CertFindCertificateInStore`. In this way we have tried to avoid the dependency of powershell command while deleting a certificate.
=> Fixing deletion of a certificate by its thumbprint.

lib/win32/certstore/store_base.rb, spec/win32/unit/certstore_spec.rb, spec/win32/unit/store_base_spec.rb
Few changes to incorporate previous PR #50 . 
- Main reason: Proper usage of  `close_cert_store`. The store handler should be closed once all its relative work is completed. This was a minor issue in previous PR that we had sent.
- Displaying error without raising and rescuing it while closing the store
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>
Few essential changes as per the review comments on previous PR #50 
[#8180](https://github.com/chef/chef/issues/8180)
=> Properly close the cert store when we're done with it & display errors

README.md, appveyor.yml
The travis tests are just to make sure we don't introduce something that
breaks chef-client on Linux, but we really care about the test results
on a windows host. Let's use the appveyor badge in the readme instead.
=> Update appveyor config and use that badge the readme

lib/win32/certstore.rb, lib/win32/certstore/store_base.rb
Allows a call to store.add_pfx to pass the dwFlags when importing the certificate into memory. 
In my use case, I needed to specify a value of CRYPT_MACHINE_KEYSET (32) in order to store the key under the local computer and not under current user.
=> Add the ability to set specify properties in add_pfx method

.expeditor/verify.pipeline.yml, Gemfile, spec/win32/unit/certstore_spec.rb, win32-certstore.gemspec
=> Require Ruby 2.5+ and test on Ruby 3.0

lib/win32/certstore/mixin/helper.rb
Signed-off-by: John McCrae <john.mccrae@progress.com>### Description
=> refactoring the helper.rb to put a default for output_path. Generic calls to cert_ps_cmd fail since they won't provide a path by default

lib/win32/certstore/mixin/helper.rb
Signed-off-by: John McCrae <jmccrae@chf.io>
We were searching for items in the Certificate store and Get-Childitem was doing a lazy search. The net effect was that downstream testing in the windows_certificate_spec.rb was failing because the rapid number of adds/removes to the cert store was not being caught by existing Get-ChildItem command. Adding the -Force switch forced it to actively search and thus return all the files we knew were there. 
=> Added the -Force command to ensure proper searches

lib/win32/certstore/store_base.rb
Signed-off-by: John McCrae <jmccrae@chf.io>
If the certificate is not found in the certificate store, we return a warning instead of a fault so we can log the error and continue running more gracefully. This is coupled with updates in windows_certificate to be more resilient to missing or expired certificates
=> Redirect for when the cert is not found.

.expeditor/verify_win32certstore.ps1, Gemfile, win32-certstore.gemspec
Updated dependencies to get ready for new Ohai for Chef-17. Specifically, we need to change the chef-powershell gem dependency. 
=> Updated dependencies to get ready for new Ohai for Chef-17
